FROM pytorch/pytorch:2.1.2-cuda11.8-cudnn8-runtime

RUN pip install transformers==4.37.* wandb==0.16.* torchvision==0.17.1 lightning==2.2.1 timm==0.9.16 accelerate==0.28.*
RUN pip install datasets==2.19.* nltk==3.8.1 sentencepiece==0.2.0