version: "3.8"

services:
  # The general app which we've instrumented
  app:
    build:
      dockerfile: Dockerfile
      context: .
      args:
        BUILDKIT_INLINE_CACHE: 1
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - .:/workspace
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
  
  torch:
    build:
      dockerfile: Dockerfile.torch-gpu
      context: .
      args:
        BUILDKIT_INLINE_CACHE: 1
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - .:/workspace
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    
  diffuser:
    build:
      dockerfile: Dockerfile.diffuser-gpu
      context: .
      args:
        BUILDKIT_INLINE_CACHE: 1
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - .:/workspace
      - ./data/container_cache:/root/.cache
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]

  ci:
    build:
      dockerfile: Dockerfile
      context: .
      args:
        BUILDKIT_INLINE_CACHE: 1
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
