version: "3.8"

services:
  # The general app which we've instrumented
  server:
    build:
      dockerfile: Dockerfile
      context: .
      args:
        BUILDKIT_INLINE_CACHE: 1
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - .:/workspace
      - ~/Datasets:/datasets
      - ~/.cache:/home/appuser/.cache
