# FROM pytorch/pytorch:2.0.0-cuda11.7-cudnn8-runtime
FROM huggingface/transformers-pytorch-gpu:4.27.3

WORKDIR /workspace
# Install pip packages
RUN --mount=type=cache,mode=0777,target=/root/.cache pip install \
    git+https://github.com/huggingface/diffusers \
    accelerate datasets wandb
# diffusers[training]
ENV DISABLE_TELEMETRY=YES