FROM pytorch/pytorch:2.0.0-cuda11.7-cudnn8-runtime

WORKDIR /workspace
# Install pip packages
RUN --mount=type=cache,mode=0777,target=/root/.cache pip install \
    lightning==2.1.3 tensorboard==2.15.1 datasets==2.16.1 wandb==0.16.1 torchmetrics==1.2.1
# Copy code
COPY . .