FROM pytorch/pytorch:2.0.0-cuda11.7-cudnn8-runtime

WORKDIR /workspace
# Install pip packages
RUN --mount=type=cache,mode=0777,target=/root/.cache pip install \
    lightning tensorboard datasets
# Copy code
# COPY . .