FROM cvlization-diffuser-gpu
RUN pip install importlib importlib-metadata torch_ema pytorch_fid_wrapper einops torchmetrics matplotlib torch-fidelity==0.3.0
RUN git config --global --add safe.directory /workspace