# FROM cvlization-torch-gpu
FROM pytorch/pytorch:2.1.2-cuda11.8-cudnn8-runtime

RUN pip install scikit-video==1.1.11 av==11.0.* wandb==0.16.* torchvision==0.17.1 lightning==2.2.1
RUN pip install einops==0.7.* moviepy==1.0.*
RUN pip install diffusers==0.26.3 timm==0.9.16