FROM pytorch/pytorch:2.3.1-cuda12.1-cudnn8-runtime


RUN pip install torchvision>=0.11.0 lightning-bolts matplotlib numpy scipy scikit-learn scprep scanpy torchdyn>=1.0.6 pot torchdiffeq absl-py clean-fid
