model:
  name: "unsloth/gpt-oss-20b"
  max_seq_length: 512
  load_in_4bit: true

lora:
  r: 8
  alpha: 16
  dropout: 0
  target_modules: ["q_proj", "k_proj", "v_proj", "o_proj"]

grpo:
  beta: 0.1  # KL divergence penalty coefficient
  temperature: 1.0
  learning_rate: 5.0e-5
  weight_decay: 0.01
  num_generations: 2
  max_steps: 10
  per_device_train_batch_size: 1
  gradient_accumulation_steps: 1
  warmup_steps: 0
  logging_steps: 1
  save_steps: 10
  output_dir: "./gpt-oss-grpo"
  seed: 42

task:
  type: "code_generation"
  prompt: |
    Create a new fast matrix multiplication function using only native Python code.
    You are given a list of list of numbers.
    Output your new function in backticks using the format below:
    ```python
    def matmul(A, B):
        return ...
    ```
