FROM pytorch/pytorch:2.1.2-cuda11.8-cudnn8-devel

RUN pip install wandb==0.16.* torchvision==0.17.1 lightning==2.2.1
RUN pip install transformers==4.40.* diffusers==0.26.3 timm==0.9.16 accelerate==0.28.* einops==0.7.* moviepy==1.0.*
