FROM tensorflow/tensorflow:2.16.1-gpu
# FROM tensorflow/tensorflow:1.15.5-gpu-py3

WORKDIR /workspace
# RUN pip install scipy==1.2.* dataclasses
RUN pip install scipy==1.13.* dataclasses
RUN pip install --ignore-installed mlflow==2.13.*